apiVersion: v1
kind: Service
metadata:
  name: {{ include "winevault.fullname" . }}
  labels:
    {{- include "winevault.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "winevault.name" . }}
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: 3000
