{{- if and (not .Values.database.existingSecret) .Values.database.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "winevault.databaseSecretName" . }}
  labels:
    {{- include "winevault.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.secretKey }}: {{ .Values.database.url | quote }}
{{- end }}
