{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "winevault.fullname" . }}-postgres
  labels:
    {{- include "winevault.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "winevault.name" . }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: 5432
  type: ClusterIP
{{- end }}
