{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "divevault.serviceAccountName" . }}
  labels:
    {{- include "divevault.labels" . | nindent 4 }}
{{- end }}
